### ISSUE TITLE
i2cset failed with error 

### ISSUE THREAD

**Issue by eboudrand** [ArduCAM/RaspberryPi#1]
When I am running init_camera.sh I got message "Error: write failed". This error is coming from command i2cset -y 1 0x70 0x00 0x04. 

i2C is enabled. I am using a raspberry pi 3 B with a supposed V2.1 Multi-Camera Adapter Board. I am not sure the distributor sold the correct adapter so I join a picture of the board.
![multicamera](https://user-images.githubusercontent.com/6330590/50723883-0e4c9a80-10e4-11e9-9988-8d01a27f37dd.jpg)

**Comment by UCTRONICS** [comment]
@eboudrand 
The version you are using is v2, not v2.1.
The v2 version doesn't need to i2cset

**Comment by eboudrand** [comment]
@UCTRONICS thank you for your feedback

**Comment by eboudrand** [comment]
Using the wrong hardware
