### ISSUE TITLE
ArduCAM UV-544 c++ control

### ISSUE THREAD

**Issue by FlYnN91** [ArduCAM/RaspberryPi#2]
Hi,

I have the ArduCAM UV-544 Rev B board connected to the CSI ribbon and I2C signals. I am using raspberry Pi 3B board. I would like to capture images via c++ application, but the examples are in Python.

I've seen the SPI_Camera folder with the demo application but if I build it and run it I get `SPI1 interface Error!` message in command line. 

Is my camera suitable for that application? I would like to autofocus and capture image using c++.

Any advise would be appreciated.

Thanks

**Comment by ArduCAM** [comment]
@FlYnN91 Please check the folder : https://github.com/ArduCAM/RaspberryPi/tree/master/Motorized_Focus_Camera 
which is for motorized focus camera module. and we only provide python version code right now.
Code in SPI_Camera is for another camera not this motorized focus camera.

**Comment by FlYnN91** [comment]
Sorry for late reply. I looked at the python example code for the motorized camera and it seems to be utilising SPI comms to talk to the camera. Could you provide the SPI communications protocol allowing me to port the python examples to C++?

I guess my only option is to get the USB version of the ArduCAM which has the C++ library. Is that correct?

**Comment by ArduCAM** [comment]
Not we don't use SPI, we use the I2C, the protocol is the standard I2C protocol.
Since you got UC-544 pi camera board, it is nothing to do with SPI and USB, just go ahead to test the camera using the code in the folder: https://github.com/ArduCAM/RaspberryPi/tree/master/Motorized_Focus_Camera

**Comment by FlYnN91** [comment]
Sorry, I did mean I2C. I would like to communicate with your camera from my C++ application so I cannot use the python scripts. Could you share the I2C protocol/messages so I can write a driver for it?

**Comment by ArduCAM** [comment]
You can find the controller from : www.arducam.com/downloads/modules/DW9714-P8.pdf and figure out the I2C protocol.

**Comment by FlYnN91** [comment]
That's perfect, thanks a lot.
