### ISSUE TITLE
Under what license is API released?

### ISSUE THREAD

**Issue by sinaaghli** [ArduCAM/RaspberryPi#36]
Hi,
I was not able to find any license files in this repo, do you guys release your API under MIT license similar to other ones (I found one under [arduino](https://github.com/ArduCAM/Arduino/blob/master/LICENSE))?

**Comment by glddiv** [comment]
@sinaaghli 
The license has been updated in commit b13807d1eb16d9f585d0b96c75ad2b54174b665e, this repository uses the BSD-3-Clause open source agreement.

**Comment by sinaaghli** [comment]
thank you
