### ISSUE TITLE
raspivid gst-launch performance

### ISSUE THREAD

**Issue by user1321** [ArduCAM/RaspberryPi#5]
Good Day!
Can you please share information about your product.
As I understood new ArduCam 2.1 is not compatible with raspivid, is it correct?
Instead we have to use /dev/video0 to get raw video (please, correct if I am wrong)
In the end too get compressed video we have to use gst-launch to compress it.
Did you check overall performance:
1. CPU load
2. Video latency comparing to raspivid

Am I wrong in that?
Thank you.

**Comment by ArduCAM** [comment]
I'm not sure what is your Arducam 2.1 referring to, can you send me more information.

**Comment by user1321** [comment]
Hi, 
Yes, sorry.
http://blog.uctronics.com/arducam-v2-1-multi-camera-adapter-board-raspberry-pi-8mp-camera-imx219/

**Comment by ArduCAM** [comment]
IT works with raspistill and raspivid software and streaming the compressed video as well as gstreamer.
The overall performance is the same as offical V2 pi camera except the improvements on lenses.

**Comment by user1321** [comment]
Got it. Thank you for your reply.
