### ISSUE TITLE
RpiCamera.py

### ISSUE THREAD

**Issue by agama949** [ArduCAM/RaspberryPi#82]
Hello,

I'm not sure if this was an isolated error, or a common error due to library update.
For getting the python programs to work I had to change the file RpiCamera.py on line 24 I replaced:
`self.cam.configure(self.cam.preview_configuration(main={"size":(width, height)},buffer_count=4)`
with (key work being create_preview_configuration)
`self.cam.configure(self.cam.create_preview_configuration(main={"size":(width, height)},buffer_count=4)`

Please let me know if this is a known issue.

**Comment by surak** [comment]
You can close this one, it's been committed: https://github.com/ArduCAM/RaspberryPi/blob/6edbde9f3fb4e866e118f6efba5940e1f5a35f09/Motorized_Focus_Camera/python/RpiCamera.py#L24
